FROM mcr.microsoft.com/playwright:v1.43.1-jammy

WORKDIR /app

# Only copy dependency declarations first
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Now copy the rest of your project
COPY . .

# Install playwright dependencies
RUN npx playwright install --with-deps

# Run tests
CMD ["npx", "playwright", "test"]
