version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - api
    environment:
      - BASE_URL=http://api:3000
    command: ["npx", "playwright", "test"]
